
image: Visual Studio 2017

environment:
  matrix:
  - MSYSTEM: MINGW64

build_script:
  - C:\msys64\usr\bin\pacman -Syuu --noconfirm
  - C:\msys64\usr\bin\bash -lc "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci/appveyor_build.sh"

