  call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"

 build:
  parallel: true                  # enable MSBuild parallel builds
  project: joycon.sln
