language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc

git:
  submodules: false

before_install:
  - sudo apt-get update
  - sudo apt-get -qq install build-essential software-properties-common
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get -qq install gcc-snapshot
  - sudo apt-get update
  - sudo apt-get -qq install gcc-6 g++-6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 100
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 100
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++
  - sudo apt-get -qq install libhidapi-dev #bluetooth api hidapi
  - sudo apt-get -qq install ninja-build #ninja

before_script:
  - mkdir build; cd build
  - cmake -G Ninja ../joycon/CMakeLists.txt

script:
  - ninja
