language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc

git:
  submodules: false
  
before_install:
  - sudo apt-get update
  - sudo apt-get clean -y
  - sudo apt-get install build-essential software-properties-common -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-snapshot -y
  - sudo apt-get update
  - sudo apt-get install gcc-6 g++-6 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 100
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 100
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++
  - sudo apt-get install libhidapi-dev -y #bluetooth api hidapi
  - sudo pip install codecov
  #- sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  
before_script:
  - mkdir build; cd build
  - cmake -DCOVERAGE=1 ../joycon/

script:
  - make
  - cd ..
  - ./get_code_cov
  - codecov
  
after_success:
  - bash <(curl -s https://codecov.io/bash);

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
