language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc

git:
  submodules: false

before_install:

	- sudo add-apt-repository -y ppa:jonathonf/gcc-7.1
	- sudo apt-get update
	- sudo apt-get -qq install gcc-7 g++-7 #gcc 7.0 for full c++14 support (and c++17)
	- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 100
	- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 100
	- sudo update-alternatives --config gcc
	- sudo update-alternatives --config g++
	- sudo apt-get -qq install libhidapi-dev #bluetooth api hidapi
	- sudo apt-get -qq install ninja-build #ninja

before_script:
	- mkdir build; cd build
	- cmake -G Ninja ../joycon/CMakeLists.txt

script:
	- ninja
